/* gci-1.vapi generated by valac 0.48.0, do not modify. */

[CCode (gir_namespace = "GCi", gir_version = "1")]
namespace GCi {
	[CCode (cheader_filename = "gci/gci.h")]
	public class EntryController : GLib.Object {
		public EntryController ();
		public EntryController.for_entry (Gtk.Entry entry);
		public Gtk.Entry entry { get; set; }
	}
}
