// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1668339680);
user_pref("browser.search.region", "ID");
user_pref("calendar.list.sortOrder", "358e505b-5c7d-4f4e-84a5-7ad670db7215");
user_pref("calendar.registry.358e505b-5c7d-4f4e-84a5-7ad670db7215.calendar-main-default", true);
user_pref("calendar.registry.358e505b-5c7d-4f4e-84a5-7ad670db7215.calendar-main-in-composite", true);
user_pref("calendar.registry.358e505b-5c7d-4f4e-84a5-7ad670db7215.disabled", true);
user_pref("calendar.registry.358e505b-5c7d-4f4e-84a5-7ad670db7215.name", "Home");
user_pref("calendar.registry.358e505b-5c7d-4f4e-84a5-7ad670db7215.type", "storage");
user_pref("calendar.registry.358e505b-5c7d-4f4e-84a5-7ad670db7215.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Jakarta");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1668339688557");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221101185644");
user_pref("extensions.lastAppVersion", "102.4.2");
user_pref("extensions.lastPlatformVersion", "102.4.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"aa6a2cdb-2797-4a0b-bff8-bcbed504e554\",\"google@search.mozilla.org\":\"80ad3583-1c3b-4218-a775-24f709ec5ac3\",\"ddg@search.mozilla.org\":\"35d9bf26-2d24-4671-9c82-01bec90a4fe9\",\"amazondotcom@search.mozilla.org\":\"26641fb5-50b1-4c78-85db-cb1c5fbd24f2\",\"wikipedia@search.mozilla.org\":\"d106fa01-8d5c-4b1b-b5e0-cb08d76f7744\",\"bing@search.mozilla.org\":\"718fa4cc-a889-43a4-8f3a-419059cd29f1\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "d15ba459-ccc4-4810-9182-868d7f584e7");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.4.2");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "58c014ab-4fa8-438f-9d32-87cc608e7fd9");
user_pref("toolkit.telemetry.previousBuildID", "20221101185644");
