// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "e8998257-43a4-4ab5-893b-cb41fa812a3b");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1668340486);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1668340466);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1668340726);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1668340606);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1668340515);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{edcc9f4d-753e-4184-b766-58befcbb4cbf}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1668340456);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{aabeb6a1-5794-4516-ac12-7f80ca2b6de0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1668340459);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1668340514179");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1668342291179");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1668340468453");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1668362068453");
user_pref("browser.search.region", "ID");
user_pref("browser.search.separatePrivateDefault.urlbarResult.enabled", false);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1668340462");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20221104133228");
user_pref("browser.startup.homepage_override.mstone", "106.0.5");
user_pref("browser.startup.lastColdStartupCheck", 1668340458);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1668340461626");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "106.0.5");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "ID");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "a8e342780654468a950b53b9a30ea15e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221104133228");
user_pref("extensions.lastAppVersion", "106.0.5");
user_pref("extensions.lastPlatformVersion", "106.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ed3c5cc5-d953-41ba-9446-4708de923cae\",\"pictureinpicture@mozilla.org\":\"3bef1bfd-2e81-4735-bcbc-d649839c96be\",\"screenshots@mozilla.org\":\"00f97484-3d1d-42ec-b9f9-5f98f8f7c11a\",\"webcompat-reporter@mozilla.org\":\"1846d791-790b-420e-8147-d56ef4db3dec\",\"webcompat@mozilla.org\":\"c8cc12d9-0989-4249-96c7-12019de5b82c\",\"default-theme@mozilla.org\":\"d848d58e-dac1-4466-adf2-e0ad151c428d\",\"addons-search-detection@mozilla.com\":\"1ed27583-7822-4cc0-992c-39cbef8524da\",\"google@search.mozilla.org\":\"bc16f006-0276-465b-a187-073094023e39\",\"amazondotcom@search.mozilla.org\":\"1e762cff-3513-4a74-b7cb-5edf72ff2d74\",\"wikipedia@search.mozilla.org\":\"ee5b078c-a2b5-45a2-bb6f-b90c48cac440\",\"bing@search.mozilla.org\":\"5616ac98-597b-4475-8c62-362fae8c599b\",\"ddg@search.mozilla.org\":\"9e955009-b7cf-456b-ba8c-cd3f12f7439b\",\"playmaker-balanced-colorway@mozilla.org\":\"45097c93-f585-4956-aaf1-f518952d3649\",\"visionary-balanced-colorway@mozilla.org\":\"65f5b07f-06a1-4b20-96f3-4d2b37574600\",\"expressionist-balanced-colorway@mozilla.org\":\"2a149f02-fb0c-43ee-bdad-3386d641a6e8\",\"dreamer-balanced-colorway@mozilla.org\":\"eee47512-7111-48b1-87bc-3bdd2ddb8758\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1668340462);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "9e4611a2-e8ce-4830-b8a0-76594a145fd2");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1668340453);
user_pref("toolkit.telemetry.cachedClientID", "a5db3a8a-fecf-492d-a872-c0852ce35c1c");
user_pref("toolkit.telemetry.previousBuildID", "20221104133228");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
