#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.10ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'cups-browsed.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/12.10ubuntu1
if [ -x "/etc/init.d/cups-browsed" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native cups-browsed stop || exit 1
fi
# End automatically added section
