#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.10ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'fprintd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/net.reactivated.Fprint.conf 1.90.1-1\~ -- "$@"
# End automatically added section
