#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/indicator-printers.desktop 0.1.7+17.04.20170227-0ubuntu1~ -- "$@"
# End automatically added section
# Automatically added by dh_icons/12.10ubuntu1
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/ubuntu-mono-dark /usr/share/icons/ubuntu-mono-light
fi
# End automatically added section
