#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.9ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'mpd.service' 'mpd.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/12.9ubuntu1
if [ -x "/etc/init.d/mpd" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native mpd stop || exit 1
fi
# End automatically added section
