#!/bin/sh

set -e

if [ "$1" = purge ]; then
    if [ -x "$(command -v deluser)" ]; then
        deluser --quiet --system nm-openvpn > /dev/null || true
    fi
    rm -rf /var/lib/openvpn/chroot
fi

# Automatically added by dh_installdeb/12.9ubuntu1
dpkg-maintscript-helper rm_conffile /etc/NetworkManager/VPN/nm-openvpn-service.name 1.2.8-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/nm-openvpn-service.conf 1.8.8-2\~ -- "$@"
# End automatically added section

