#!/bin/sh
set -e
# Automatically added by dh_installsystemduser/12.9ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user mask 'rygel.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'rygel.service' >/dev/null || true
		deb-systemd-helper --user unmask 'rygel.service' >/dev/null || true
	fi
fi
# End automatically added section
