#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.10ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'spice-vdagentd.service' 'spice-vdagentd.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/12.10ubuntu1
if [ -x "/etc/init.d/spice-vdagent" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native spice-vdagent stop || exit 1
fi
# End automatically added section
